# Generated by Django 4.1 on 2022-09-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_expired_bottle_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='in_stock',
            new_name='expired',
        ),
    ]
