# Generated by Django 4.1 on 2022-09-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_in_stock_bottle_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='expired',
            new_name='in_stock',
        ),
    ]
