# Generated by Django 4.1.1 on 2022-09-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_order_options_remove_client_user_and_more'),
        ('core', '0004_rename_expired_bottle_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='orders',
        ),
        migrations.AddField(
            model_name='bottle',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='volume',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_count', to='clients.order'),
        ),
    ]
