# Generated by Django 4.1 on 2022-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Является активным покупателем!'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bottles_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
